Sat Apr 27 2024 13:33:0 } [PH] error: 
Invalid `prisma.appointment.findMany()` invocation:


error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:10
   | 
 9 |   provider = "postgresql"
10 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
Sat Apr 27 2024 13:34:0 } [PH] error: 
Invalid `prisma.appointment.findMany()` invocation:


Authentication failed against database server at `localhost`, the provided database credentials for `USERNAME` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
Sat Apr 27 2024 13:35:0 } [PH] error: 
Invalid `prisma.appointment.findMany()` invocation:


Authentication failed against database server at `localhost`, the provided database credentials for `USERNAME` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
Sat Apr 27 2024 13:36:0 } [PH] error: 
Invalid `prisma.appointment.findMany()` invocation:


Authentication failed against database server at `localhost`, the provided database credentials for `USERNAME` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
Sat Apr 27 2024 13:37:0 } [PH] error: 
Invalid `prisma.appointment.findMany()` invocation:


Authentication failed against database server at `localhost`, the provided database credentials for `USERNAME` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
Sat Apr 27 2024 13:38:0 } [PH] error: 
Invalid `prisma.appointment.findMany()` invocation:


Authentication failed against database server at `localhost`, the provided database credentials for `USERNAME` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
Sat Apr 27 2024 13:39:0 } [PH] error: 
Invalid `prisma.appointment.findMany()` invocation:


Authentication failed against database server at `localhost`, the provided database credentials for `USERNAME` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
Sat Apr 27 2024 13:40:0 } [PH] error: 
Invalid `prisma.appointment.findMany()` invocation:


Database `DATABASE` does not exist on the database server at `localhost:5432`.
